/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pulkit_WinRegKeyName */

#ifndef _Included_pulkit_WinRegKeyName
#define _Included_pulkit_WinRegKeyName
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pulkit_WinRegKeyName
 * Method:    nextElement
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pulkit_WinRegKeyName_nextElement
  (JNIEnv *, jobject);

/*
 * Class:     pulkit_WinRegKeyName
 * Method:    hasMoreElements
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_pulkit_WinRegKeyName_hasMoreElements
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
