/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pulkit_SystemInfo */

#ifndef _Included_pulkit_SystemInfo
#define _Included_pulkit_SystemInfo
#ifdef __cplusplus
extern "C" {
#endif
#undef pulkit_SystemInfo_HKEY_LOCAL_MACHINE
#define pulkit_SystemInfo_HKEY_LOCAL_MACHINE -2147483646L
/*
 * Class:     pulkit_SystemInfo
 * Method:    getValue
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_pulkit_SystemInfo_getValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     pulkit_SystemInfo
 * Method:    setValue
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_pulkit_SystemInfo_setValue
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
