/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package pulkit;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
/**
 * This class handles the event generated by the object of
 * GuiUsbPlayer
 * @author pulkit saxena
 * Date 5-Jan-2007
 */
public class GuiUsbPlayerEvntHandler implements ActionListener {
  GuiUsbPlayer objGuGuiUsbPlayerUsbPlayer;
   
  /**
   * Constructor
   * @param objGuGuiUsbPlayeriUsbPlayer
   */
  public GuiUsbPlayerEvntHandler(GuiUsbPlayer objGuGuiUsbPlayeriUsbPlayer){
     this.objGuGuiUsbPlayerUsbPlayer =objGuGuiUsbPlayerUsbPlayer; 
      
  }
  
  
/**
 * This function handles the event generated 
 * @param ae
 */
public void actionPerformed(ActionEvent ae) {
 
       //to recognise who created event
	 String arg=(String)ae.getActionCommand();
        
         //event handling for USB enabling
 if(arg.equals("Enable-USB"))
   {
            SystemInfo key = new SystemInfo(SystemInfo.HKEY_LOCAL_MACHINE,
                "SYSTEM\\CurrentControlSet\\Services\\USBSTOR");
            Enumeration  e =key.names();
            List keyNames = new LinkedList();
            while(e.hasMoreElements())
               {
            
               String name =(String)e.nextElement();
               keyNames.add(name);
                }
       
   if(keyNames.contains("Start"))
    {
          Object value = key.getValue("Start");        
     
      if(value.equals(new Integer(3)))
            {
          JOptionPane.showMessageDialog (objGuGuiUsbPlayerUsbPlayer,new 
	     	  String("USB already enabled-Select Help if not enabled "));
            }  
     
      else
            {
              key.setValue("Start",new Integer(3));    
              JOptionPane.showMessageDialog (objGuGuiUsbPlayerUsbPlayer,new 
	   		    	  String("USB enabled Select Help further ")); 	  
           }
     }
   else
          {
              JOptionPane.showMessageDialog (objGuGuiUsbPlayerUsbPlayer,new 
	   		    	  String("USB Key not found See Help "));            
          }
    
     }
    

  //event handled for USB disabling       
 else if(arg.equals("Disable-USB"))     
 {
     SystemInfo key = new SystemInfo(SystemInfo.HKEY_LOCAL_MACHINE,
                "SYSTEM\\CurrentControlSet\\Services\\USBSTOR");
            Enumeration  e =key.names();
            List keyNames = new LinkedList();
            while(e.hasMoreElements())
               {
            
               String name =(String)e.nextElement();
               keyNames.add(name);
                }
       
   if(keyNames.contains("Start"))
    {
          Object value = key.getValue("Start");        
     
      if(value.equals(new Integer(4)))
            {
        JOptionPane.showMessageDialog (objGuGuiUsbPlayerUsbPlayer,new 
	 	  String("USB already disabled "));  
            }  
     
      else
            {
              key.setValue("Start",new Integer(4));    
              JOptionPane.showMessageDialog (objGuGuiUsbPlayerUsbPlayer,new 
	   		    	  String("USB Disabled ")); 	  
           }
     }
   else
          {
              JOptionPane.showMessageDialog (objGuGuiUsbPlayerUsbPlayer,new 
	   		    	  String("USB Key not found See Help "));            
          }
     
 } 
 
 //event handled for menu item exit
 else if(arg.equals("Exit")) 
 {
     System.exit(0);
 }    
         
 else if(arg.equals("Usb-Help"))
 {
  try {
      String cmd ="cmd.exe /c start ";
	 String usbKnow ="USBHelp.chm";
  	 //invoking native method
        Runtime.getRuntime().exec(cmd+usbKnow);
	 }catch(Exception ex) 
         {	
          JOptionPane.showMessageDialog (objGuGuiUsbPlayerUsbPlayer,new 
	  String("help exe not found"+ex)); 	  
	 }	     
   }   
 
 /* removed later        
 else if(arg.equals("About"))
  {
   try {
      String cmd ="cmd.exe /c start ";
	 String about ="about.pdf";
  	 //invoking native method
        Runtime.getRuntime().exec(cmd+about);
	 }catch(Exception ex) 
         {	
          JOptionPane.showMessageDialog (objGuGuiUsbPlayerUsbPlayer,new 
	  String("File not found /PDF Reader nor found "+ex)); 	  
	 }	        
      
  }*/
  else if(arg.equals("Mail-id"))
  {
    JOptionPane.showMessageDialog (objGuGuiUsbPlayerUsbPlayer,new 
	  String("Give your feedback at: pulkit2sha@gmail.com "));  
      
  }
         
         
}
}
